import { StyleId, StyleProfile } from './style-types';

// ═══════════════════════════════════════════════════════════════════
//  MINIMAL SWISS
//  Inspired by the International Typographic Style (Swiss Design).
//  Restrained palette, mathematical grid, Helvetica-adjacent type,
//  zero ornamentation — every pixel has a reason to exist.
//  Think: Dieter Rams meets Josef Müller-Brockmann.
// ═══════════════════════════════════════════════════════════════════

export const swissProfile: StyleProfile = {
  id: 'swiss',
  name: 'Minimal Swiss',
  description:
    'Precision grid typography, restrained palette, and zero ornamentation. Every element has mathematical purpose.',
  fontFamily: 'Manrope',
  fontDisplay: 'Manrope',
  tokens: {
    light: {
      background: '0 0% 98%',
      foreground: '0 0% 9%',
      card: '0 0% 100%',
      'card-foreground': '0 0% 9%',
      popover: '0 0% 100%',
      'popover-foreground': '0 0% 9%',
      primary: '0 0% 9%',
      'primary-foreground': '0 0% 98%',
      secondary: '0 0% 94%',
      'secondary-foreground': '0 0% 20%',
      muted: '0 0% 95%',
      'muted-foreground': '0 0% 45%',
      accent: '0 0% 94%',
      'accent-foreground': '0 0% 9%',
      destructive: '0 72% 51%',
      'destructive-foreground': '0 0% 100%',
      border: '0 0% 89%',
      input: '0 0% 89%',
      ring: '0 0% 9%',
      radius: '0.125rem',
      'sidebar-background': '0 0% 96%',
      'sidebar-foreground': '0 0% 20%',
      'sidebar-primary': '0 0% 9%',
      'sidebar-primary-foreground': '0 0% 98%',
      'sidebar-accent': '0 0% 92%',
      'sidebar-accent-foreground': '0 0% 20%',
      'sidebar-border': '0 0% 89%',
      'sidebar-ring': '0 0% 9%',
    },
    dark: {
      background: '0 0% 6%',
      foreground: '0 0% 93%',
      card: '0 0% 9%',
      'card-foreground': '0 0% 93%',
      popover: '0 0% 9%',
      'popover-foreground': '0 0% 93%',
      primary: '0 0% 93%',
      'primary-foreground': '0 0% 9%',
      secondary: '0 0% 14%',
      'secondary-foreground': '0 0% 80%',
      muted: '0 0% 14%',
      'muted-foreground': '0 0% 55%',
      accent: '0 0% 14%',
      'accent-foreground': '0 0% 93%',
      destructive: '0 72% 51%',
      'destructive-foreground': '0 0% 100%',
      border: '0 0% 18%',
      input: '0 0% 18%',
      ring: '0 0% 93%',
      radius: '0.125rem',
      'sidebar-background': '0 0% 8%',
      'sidebar-foreground': '0 0% 80%',
      'sidebar-primary': '0 0% 93%',
      'sidebar-primary-foreground': '0 0% 9%',
      'sidebar-accent': '0 0% 14%',
      'sidebar-accent-foreground': '0 0% 80%',
      'sidebar-border': '0 0% 18%',
      'sidebar-ring': '0 0% 93%',
    },
    borderWidth: '1px',
    opacity: 1,
    blur: '0px',
    elevation: 0,
  },
  composition: {
    spacingUnit: 4,
    density: 'compact',
    panelGap: '1px',
    cardPadding: '1.25rem',
    sectionGap: '1.5rem',
    layoutMode: 'grid',
  },
  components: {
    card: 'border border-border shadow-none rounded-sm',
    button: 'rounded-sm font-medium tracking-wide uppercase text-xs',
    input: 'rounded-sm border-border',
    badge: 'rounded-none font-mono uppercase text-[10px] tracking-widest',
    nav: 'tracking-wide uppercase text-xs',
    tab: 'rounded-none border-b-2 border-transparent data-[state=active]:border-foreground',
    separator: 'bg-border',
  },
  motion: {
    enabled: true,
    duration: '120ms',
    easing: 'cubic-bezier(0, 0, 0.2, 1)',
    stagger: 30,
    hoverScale: 1,
    enterAnimation: 'fade',
  },
  surface: {
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderWidth: '1px',
    shadowStyle: 'none',
    backgroundOpacity: 1,
    noise: false,
    glowEffect: false,
    borderColor: 'inherit',
  },
};

// ═══════════════════════════════════════════════════════════════════
//  GLASSMORPHISM
//  Frosted translucency, depth through layered blur, iridescent
//  highlights, soft luminance. Ethereal and atmospheric — like
//  peering through rain-streaked glass at neon city lights.
//  Think: Apple Vision Pro meets a Blade Runner 2049 terminal.
// ═══════════════════════════════════════════════════════════════════

export const glassProfile: StyleProfile = {
  id: 'glass',
  name: 'Glassmorphism',
  description:
    'Frosted glass panels with luminous depth. Layered translucency creates an ethereal, atmospheric interface.',
  fontFamily: 'Manrope',
  fontDisplay: 'Manrope',
  tokens: {
    light: {
      background: '220 25% 95%',
      foreground: '225 20% 18%',
      card: '220 30% 98%',
      'card-foreground': '225 20% 18%',
      popover: '220 30% 98%',
      'popover-foreground': '225 20% 18%',
      primary: '230 65% 55%',
      'primary-foreground': '0 0% 100%',
      secondary: '220 20% 92%',
      'secondary-foreground': '225 20% 30%',
      muted: '220 15% 90%',
      'muted-foreground': '225 12% 50%',
      accent: '260 50% 60%',
      'accent-foreground': '0 0% 100%',
      destructive: '0 72% 51%',
      'destructive-foreground': '0 0% 100%',
      border: '220 20% 85%',
      input: '220 20% 88%',
      ring: '230 65% 55%',
      radius: '0.75rem',
      'sidebar-background': '220 25% 93%',
      'sidebar-foreground': '225 20% 25%',
      'sidebar-primary': '230 65% 55%',
      'sidebar-primary-foreground': '0 0% 100%',
      'sidebar-accent': '260 40% 92%',
      'sidebar-accent-foreground': '225 20% 25%',
      'sidebar-border': '220 20% 85%',
      'sidebar-ring': '230 65% 55%',
    },
    dark: {
      background: '225 25% 8%',
      foreground: '220 15% 90%',
      card: '225 20% 12%',
      'card-foreground': '220 15% 90%',
      popover: '225 20% 12%',
      'popover-foreground': '220 15% 90%',
      primary: '230 70% 65%',
      'primary-foreground': '225 25% 8%',
      secondary: '225 15% 18%',
      'secondary-foreground': '220 15% 85%',
      muted: '225 15% 16%',
      'muted-foreground': '220 10% 55%',
      accent: '260 55% 65%',
      'accent-foreground': '0 0% 100%',
      destructive: '0 72% 51%',
      'destructive-foreground': '0 0% 100%',
      border: '225 15% 20%',
      input: '225 15% 20%',
      ring: '230 70% 65%',
      radius: '0.75rem',
      'sidebar-background': '225 20% 10%',
      'sidebar-foreground': '220 15% 80%',
      'sidebar-primary': '230 70% 65%',
      'sidebar-primary-foreground': '0 0% 100%',
      'sidebar-accent': '260 30% 20%',
      'sidebar-accent-foreground': '220 15% 85%',
      'sidebar-border': '225 15% 20%',
      'sidebar-ring': '230 70% 65%',
    },
    borderWidth: '1px',
    opacity: 0.7,
    blur: '16px',
    elevation: 2,
  },
  composition: {
    spacingUnit: 8,
    density: 'comfortable',
    panelGap: '1rem',
    cardPadding: '1.5rem',
    sectionGap: '2rem',
    layoutMode: 'stack',
  },
  components: {
    card: 'rounded-xl border border-white/20 shadow-lg',
    button: 'rounded-lg font-medium',
    input: 'rounded-lg border-white/20',
    badge: 'rounded-full font-medium',
    nav: 'font-medium',
    tab: 'rounded-lg data-[state=active]:bg-white/10',
    separator: 'bg-white/10',
  },
  motion: {
    enabled: true,
    duration: '300ms',
    easing: 'cubic-bezier(0.16, 1, 0.3, 1)',
    stagger: 60,
    hoverScale: 1.02,
    enterAnimation: 'scale',
  },
  surface: {
    backdropBlur: '16px',
    borderStyle: 'solid',
    borderWidth: '1px',
    shadowStyle: '0 8px 32px rgba(0, 0, 0, 0.12)',
    backgroundOpacity: 0.7,
    noise: false,
    glowEffect: true,
    borderColor: 'rgba(255, 255, 255, 0.18)',
  },
};

// ═══════════════════════════════════════════════════════════════════
//  NEUBRUTALISM
//  Thick borders, harsh offset shadows, clashing saturated colors,
//  raw chunky type. Anti-polish. Maximum impact through deliberate
//  visual collision. Every element screams for attention equally.
//  Think: Memphis Group meets Y2K web aesthetic meets Gumby.
// ═══════════════════════════════════════════════════════════════════

export const neubrutalProfile: StyleProfile = {
  id: 'neubrutalism',
  name: 'Neubrutalism',
  description:
    'Thick borders, offset shadows, clashing saturated colors. Raw visual impact through deliberate collision.',
  fontFamily: 'Manrope',
  fontDisplay: 'Manrope',
  tokens: {
    light: {
      background: '50 100% 96%',
      foreground: '0 0% 5%',
      card: '50 100% 97%',
      'card-foreground': '0 0% 5%',
      popover: '50 100% 97%',
      'popover-foreground': '0 0% 5%',
      primary: '263 70% 55%',
      'primary-foreground': '50 100% 97%',
      secondary: '160 85% 45%',
      'secondary-foreground': '0 0% 5%',
      muted: '45 80% 88%',
      'muted-foreground': '0 0% 30%',
      accent: '340 82% 55%',
      'accent-foreground': '50 100% 97%',
      destructive: '0 90% 55%',
      'destructive-foreground': '0 0% 100%',
      border: '0 0% 5%',
      input: '0 0% 5%',
      ring: '263 70% 55%',
      radius: '0rem',
      'sidebar-background': '200 90% 55%',
      'sidebar-foreground': '0 0% 5%',
      'sidebar-primary': '0 0% 5%',
      'sidebar-primary-foreground': '50 100% 97%',
      'sidebar-accent': '50 100% 65%',
      'sidebar-accent-foreground': '0 0% 5%',
      'sidebar-border': '0 0% 5%',
      'sidebar-ring': '263 70% 55%',
    },
    dark: {
      background: '260 20% 10%',
      foreground: '50 100% 95%',
      card: '260 15% 14%',
      'card-foreground': '50 100% 95%',
      popover: '260 15% 14%',
      'popover-foreground': '50 100% 95%',
      primary: '50 100% 60%',
      'primary-foreground': '260 20% 10%',
      secondary: '160 80% 50%',
      'secondary-foreground': '260 20% 10%',
      muted: '260 15% 20%',
      'muted-foreground': '50 40% 70%',
      accent: '340 82% 60%',
      'accent-foreground': '50 100% 95%',
      destructive: '0 90% 55%',
      'destructive-foreground': '0 0% 100%',
      border: '50 100% 95%',
      input: '50 100% 95%',
      ring: '50 100% 60%',
      radius: '0rem',
      'sidebar-background': '260 15% 14%',
      'sidebar-foreground': '50 100% 95%',
      'sidebar-primary': '50 100% 60%',
      'sidebar-primary-foreground': '260 20% 10%',
      'sidebar-accent': '340 80% 55%',
      'sidebar-accent-foreground': '50 100% 95%',
      'sidebar-border': '50 100% 95%',
      'sidebar-ring': '50 100% 60%',
    },
    borderWidth: '3px',
    opacity: 1,
    blur: '0px',
    elevation: 0,
  },
  composition: {
    spacingUnit: 8,
    density: 'spacious',
    panelGap: '0.75rem',
    cardPadding: '1.25rem',
    sectionGap: '1.5rem',
    layoutMode: 'loose',
  },
  components: {
    card: 'rounded-none border-[3px] border-foreground shadow-[4px_4px_0px_0px] shadow-foreground',
    button:
      'rounded-none border-[3px] border-foreground shadow-[3px_3px_0px_0px] shadow-foreground font-black uppercase tracking-wide active:translate-x-[3px] active:translate-y-[3px] active:shadow-none transition-all',
    input: 'rounded-none border-[3px] border-foreground',
    badge:
      'rounded-none border-[2px] border-foreground font-black uppercase text-xs shadow-[2px_2px_0px_0px] shadow-foreground',
    nav: 'font-black uppercase tracking-wide',
    tab: 'rounded-none border-[2px] border-transparent data-[state=active]:border-foreground data-[state=active]:shadow-[2px_2px_0px_0px] data-[state=active]:shadow-foreground font-bold uppercase',
    separator: 'bg-foreground h-[3px]',
  },
  motion: {
    enabled: true,
    duration: '100ms',
    easing: 'cubic-bezier(0, 0, 0, 1)',
    stagger: 20,
    hoverScale: 1.03,
    enterAnimation: 'slide-up',
  },
  surface: {
    backdropBlur: '0px',
    borderStyle: 'solid',
    borderWidth: '3px',
    shadowStyle: '4px 4px 0px 0px',
    backgroundOpacity: 1,
    noise: true,
    glowEffect: false,
    borderColor: 'currentColor',
  },
};

// ─── Profile Registry ─────────────────────────────────────────────

export const styleProfiles: Record<StyleId, StyleProfile> = {
  swiss: swissProfile,
  glass: glassProfile,
  neubrutalism: neubrutalProfile,
};

export const styleProfileList: StyleProfile[] = Object.values(styleProfiles);

export function getStyleProfile(id: StyleId): StyleProfile {
  return styleProfiles[id];
}
